name: Publish Npm Package
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org/
      - run: npm i && npm run init
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: build-dist
          path: ./example/build
      - uses: actions/upload-artifact@v4
        with:
          name: npm-dist
          path: |
            ./
            !./.*
            !./src
            !./node_modules
            !./.github
            !./package-lock.json
            !./doc
            !./example
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: npm-dist
          path: ./
      - uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org/
      - name: Publish Npm
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.KNE_PACKAGE_PUBLISH}}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build-dist
          path: ./
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
