name: Publish Npm Package
on:
  push:
    branches: [ master ]
jobs:
  build:
    if: github.event.pull_request.merged == true
    steps:
      - run: npm i && npm run init
      - run: npm run build
  deploy:
    needs: build
    steps:
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./example/build
