name: Publish Npm Package
on:
  push:
    branches: [ master ]
jobs:
  build:
    if: github.event.pull_request.merged == true
    uses: kne-union/actions/.github/workflows/publish-libs-workflow.yml@master
    secrets: inherit
    with:
      package_name: '@kne/use-resize'
      example_package_name: '@kne-components/use-resize'
  deploy:
    uses: peaceiris/actions-gh-pages@v4
    needs: build
    with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      publish_dir: ./example/build
